In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('ONINE_FOOD_DELIVERY_ANALYSIS.csv')
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 100000
Columns: 25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

In [ ]:
missing = df.isnull().sum()

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': round((missing/len(df))*100,2)
})

missing_df.sort_values('Missing %', ascending=False)

                     Missing Count  Missing %
Cancellation_Reason          90969      90.97
Final_Amount                 55697      55.70
Customer_Age                 50093      50.09
Distance_km                  33470      33.47
Delivery_Time_Min            33359      33.36
Order_Value                  33327      33.33
Peak_Hour                    32962      32.96
Customer_Gender              24856      24.86
Payment_Mode                 19911      19.91
Cuisine_Type                 16885      16.89
City                         16726      16.73
Discount_Applied             16715      16.72
Area                         16685      16.68
Delivery_Rating              16523      16.52
Order_Time                    1998       2.00
Order_Date                    1014       1.01
Order_ID                         0       0.00
Restaurant_Name                  0       0.00
Restaurant_ID                    0       0.00
Customer_ID                      0       0.00
Order_Status                     0       0.00
Delivery_Partner_ID              0       0.00
Restaurant_Rating                0       0.00
Order_Day                        0       0.00
Profit_Margin                    0       0.00

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
for col in df.columns:
    print(col, df[col].nunique())

Order_ID 100000
Customer_ID 8999
Customer_Age 43
Customer_Gender 3
City 5
Area 5
Restaurant_ID 900
Restaurant_Name 500
Cuisine_Type 5
Order_Date 365
Order_Time 1
Delivery_Time_Min 232
Distance_km 3402
Order_Value 4052
Discount_Applied 5
Final_Amount 4574
Payment_Mode 4
Order_Status 2
Cancellation_Reason 3
Delivery_Partner_ID 900
Delivery_Rating 5
Restaurant_Rating 26
Order_Day 2
Peak_Hour 2
Profit_Margin 71

In [ ]:
df.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [ ]:
df[df['Delivery_Rating'] > 5]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Age, Customer_Gender, City, Area, Restaurant_ID, Restaurant_Name, Cuisine_Type, Order_Date, Order_Time, Delivery_Time_Min, Distance_km, Order_Value, Discount_Applied, Final_Amount, Payment_Mode, Order_Status, Cancellation_Reason, Delivery_Partner_ID, Delivery_Rating, Restaurant_Rating, Order_Day, Peak_Hour, Profit_Margin]
Index: []

[0 rows x 25 columns]

In [ ]:
df[df['Profit_Margin'] < 0]

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
14,ORD000015,CUST8064,28.0,NaN,Delhi,East,RES418,Restaurant_455,Mexican,5/15/2024,...,3717.0,UPI,Delivered,NaN,DP219,4.0,4.8,Weekday,False,-0.01
17,ORD000018,CUST2861,NaN,NaN,Hyderabad,West,RES562,Restaurant_51,Arabian,7/26/2024,...,NaN,Card,Delivered,NaN,DP721,5.0,3.4,Weekday,False,-0.09
18,ORD000019,CUST1044,52.0,Female,Delhi,East,RES568,Restaurant_43,Chinese,3/6/2024,...,NaN,Card,Delivered,NaN,DP847,1.0,3.0,Weekday,NaN,-0.16
20,ORD000021,CUST1786,NaN,NaN,Mumbai,North,RES434,Restaurant_499,NaN,10/12/2024,...,255.0,Wallet,Delivered,NaN,DP525,NaN,4.5,Weekend,False,-0.11
25,ORD000026,CUST2566,24.0,Female,Delhi,North,RES371,Restaurant_154,Indian,4/22/2024,...,463.0,Card,Delivered,NaN,DP425,1.0,5.2,Weekday,False,-0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99982,ORD099983,CUST3056,44.0,Male,Hyderabad,East,RES583,Restaurant_495,Chinese,6/26/2024,...,NaN,COD,Delivered,NaN,DP814,5.0,5.1,Weekday,NaN,-0.10
99986,ORD099987,CUST3286,NaN,NaN,Mumbai,NaN,RES647,Restaurant_223,NaN,6/12/2024,...,3728.0,NaN,Delivered,NaN,DP198,NaN,3.4,Weekday,False,-0.14
99987,ORD099988,CUST3525,43.0,Male,NaN,NaN,RES443,Restaurant_62,Chinese,4/26/2024,...,593.0,NaN,Delivered,NaN,DP276,5.0,5.2,Weekday,True,-0.13
99994,ORD099995,CUST9174,NaN,Female,Delhi,East,RES596,Restaurant_342,Italian,4/12/2024,...,NaN,NaN,Cancelled,NaN,DP682,2.0,5.3,Weekday,NaN,-0.15
99996,ORD099997,CUST6158,NaN,Male,Mumbai,East,RES157,Restaurant_458,Arabian,4/22/2024,...,1078.0,NaN,Delivered,NaN,DP476,4.0,3.5,Weekday,False,-0.15

In [ ]:
pd.crosstab(
    df['Order_Status'],
    df['Cancellation_Reason'].isnull()
)

Cancellation_Reason  False  True
Order_Status
Cancelled             9031   6005
Delivered                0  84964

In [ ]:
sample = df[
    df['Final_Amount'].notna() &
    df['Order_Value'].notna() &
    df['Discount_Applied'].notna()
]

sample[['Order_Value',
        'Discount_Applied',
        'Final_Amount']].head(20)

    Order_Value  Discount_Applied  Final_Amount
1        4869.0              20.0        4849.0
2         757.0              20.0         737.0
4         372.0              20.0         352.0
7        3506.0              20.0        3486.0
8         525.0             100.0         425.0
9        4691.0              50.0        4641.0
10       4881.0             100.0        4781.0
12        417.0              20.0         397.0
14       4017.0             300.0        3717.0
16       4218.0              20.0        4198.0
20        355.0             100.0         255.0
21       1046.0             300.0         746.0
22       1060.0              50.0        1010.0
25        483.0              20.0         463.0
29       2553.0              50.0        2503.0
35        999.0             100.0         899.0
38        672.0              50.0         622.0
40       1126.0              20.0        1106.0
42        870.0              50.0         820.0
47       4084.0             300.0        3784.0

In [ ]:
df[df['Final_Amount'] < 0]

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
104,ORD000105,CUST8820,NaN,Female,Delhi,South,RES159,Restaurant_229,Mexican,9/11/2024,...,-113.0,NaN,Delivered,NaN,DP420,3.0,4.7,Weekday,False,0.16
132,ORD000133,CUST5296,57.0,Other,Chennai,East,RES772,Restaurant_461,Indian,3/14/2024,...,-125.0,COD,Delivered,NaN,DP423,2.0,3.8,Weekday,NaN,0.12
284,ORD000285,CUST5963,44.0,NaN,Chennai,East,RES482,Restaurant_286,Italian,9/24/2024,...,-54.0,Wallet,Delivered,NaN,DP936,4.0,4.2,Weekday,True,-0.01
306,ORD000307,CUST7962,19.0,NaN,Delhi,East,RES351,Restaurant_238,Arabian,11/9/2024,...,-106.0,UPI,Delivered,NaN,DP183,3.0,4.3,Weekend,True,0.30
359,ORD000360,CUST7405,30.0,Other,NaN,East,RES857,Restaurant_32,Arabian,5/16/2024,...,-15.0,UPI,Delivered,NaN,DP308,NaN,4.1,Weekday,False,-0.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99645,ORD099646,CUST2374,NaN,NaN,Chennai,East,RES604,Restaurant_269,Mexican,2/1/2024,...,-75.0,COD,Delivered,NaN,DP994,3.0,4.1,Weekday,NaN,0.16
99681,ORD099682,CUST8915,51.0,Female,Bangalore,South,RES723,Restaurant_133,Chinese,1/21/2024,...,-84.0,NaN,Cancelled,Late Delivery,DP621,NaN,3.5,Weekend,NaN,-0.07
99870,ORD099871,CUST8481,49.0,Female,NaN,Central,RES490,Restaurant_164,Chinese,7/4/2024,...,-15.0,Card,Delivered,NaN,DP148,3.0,5.0,Weekday,NaN,0.46
99939,ORD099940,CUST5924,59.0,NaN,Hyderabad,North,RES874,Restaurant_107,Mexican,5/11/2024,...,-116.0,NaN,Delivered,NaN,DP782,4.0,3.9,Weekend,False,0.27
99961,ORD099962,CUST6135,NaN,Male,Delhi,East,RES668,Restaurant_469,Arabian,8/30/2024,...,-126.0,Wallet,Delivered,NaN,DP764,4.0,3.9,Weekday,NaN,-0.10

In [ ]:
df[df['Restaurant_Rating'] > 5]

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
19,ORD000020,CUST8005,53.0,Male,Bangalore,East,RES876,Restaurant_227,Mexican,2/4/2024,...,NaN,COD,Delivered,NaN,DP653,5.0,5.4,Weekend,True,0.29
24,ORD000025,CUST9940,45.0,Other,Chennai,NaN,RES953,Restaurant_189,Italian,11/7/2024,...,NaN,Wallet,Delivered,NaN,DP416,4.0,5.1,Weekday,True,0.45
25,ORD000026,CUST2566,24.0,Female,Delhi,North,RES371,Restaurant_154,Indian,4/22/2024,...,463.0,Card,Delivered,NaN,DP425,1.0,5.2,Weekday,False,-0.01
27,ORD000028,CUST4677,34.0,Other,Mumbai,North,RES402,Restaurant_66,Mexican,5/14/2024,...,NaN,UPI,Delivered,NaN,DP725,3.0,5.3,Weekday,True,-0.05
33,ORD000034,CUST1629,NaN,Male,Bangalore,West,RES910,Restaurant_419,Indian,1/2/2024,...,NaN,UPI,Delivered,NaN,DP712,3.0,5.1,Weekday,NaN,0.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99976,ORD099977,CUST8271,NaN,Male,Mumbai,West,RES534,Restaurant_380,Mexican,10/15/2024,...,655.0,NaN,Delivered,NaN,DP250,5.0,5.2,Weekday,False,0.08
99977,ORD099978,CUST5981,19.0,Female,NaN,Central,RES329,Restaurant_496,Indian,5/5/2024,...,NaN,UPI,Delivered,NaN,DP961,4.0,5.5,Weekend,False,0.30
99982,ORD099983,CUST3056,44.0,Male,Hyderabad,East,RES583,Restaurant_495,Chinese,6/26/2024,...,NaN,COD,Delivered,NaN,DP814,5.0,5.1,Weekday,NaN,-0.10
99987,ORD099988,CUST3525,43.0,Male,NaN,NaN,RES443,Restaurant_62,Chinese,4/26/2024,...,593.0,NaN,Delivered,NaN,DP276,5.0,5.2,Weekday,True,-0.13
99994,ORD099995,CUST9174,NaN,Female,Delhi,East,RES596,Restaurant_342,Italian,4/12/2024,...,NaN,NaN,Cancelled,NaN,DP682,2.0,5.3,Weekday,NaN,-0.15

In [ ]:
df[df['Restaurant_Rating'] > 5].shape

(18019, 25)

In [ ]:
df[df['Profit_Margin'] < 0].shape

(27733, 25)

In [ ]:
df[df['Final_Amount'] < 0].shape

(773, 25)

In [5]:
df[df['Restaurant_Rating'] > 5]['Restaurant_Rating'].value_counts()

Restaurant_Rating
5.2    4054
5.1    4031
5.3    4016
5.4    3876
5.5    2042
Name: count, dtype: int64

In [7]:
df['Restaurant_Rating'] = np.where(
    df['Restaurant_Rating'] > 5,
    5,
    df['Restaurant_Rating']
)

In [8]:
df[df['Restaurant_Rating'] > 5]['Restaurant_Rating'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df['Peak_Hour'].value_counts(dropna=False)

Peak_Hour
False    33585
True     33453
NaN      32962
Name: count, dtype: int64

In [ ]:
df[df['Final_Amount'] < 0][[
    'Order_Value',
    'Discount_Applied',
    'Final_Amount'
]].head(20)

      Order_Value  Discount_Applied  Final_Amount
104         187.0             300.0        -113.0
132         175.0             300.0        -125.0
284         246.0             300.0         -54.0
306         194.0             300.0        -106.0
359         285.0             300.0         -15.0
576         247.0             300.0         -53.0
619         234.0             300.0         -66.0
729         210.0             300.0         -90.0
891         195.0             300.0        -105.0
1148        204.0             300.0         -96.0
1517        254.0             300.0         -46.0
1589        245.0             300.0         -55.0
1683        286.0             300.0         -14.0
1777        210.0             300.0         -90.0
1813        167.0             300.0        -133.0
2099        295.0             300.0          -5.0
2149        221.0             300.0         -79.0
2705        176.0             300.0        -124.0
2871        298.0             300.0          -2.0
2904        252.0             300.0         -48.0

In [ ]:
numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    print(f"\n{col}")

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print("Outliers:", len(outliers))

Customer_Age
Outliers: 0

Delivery_Time_Min
Outliers: 0

Distance_km
Outliers: 0

Order_Value
Outliers: 0

Discount_Applied
Outliers: 16600

Final_Amount
Outliers: 0

Delivery_Rating
Outliers: 0

Restaurant_Rating
Outliers: 0

Profit_Margin
Outliers: 0

In [6]:
df['Restaurant_Rating'] = df['Restaurant_Rating'].clip(upper=5)