In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('ONINE_FOOD_DELIVERY_ANALYSIS.csv')

df.shape

(100000, 25)

In [4]:
df_clean = df.copy()

In [5]:
df_clean['Order_Date'] = pd.to_datetime(
    df_clean['Order_Date'],
    errors='coerce'
)

In [6]:
df_clean['Order_Time'].dropna().head(10)

0    0:00
1    0:00
2    0:00
3    0:00
4    0:00
5    0:00
6    0:00
7    0:00
8    0:00
9    0:00
Name: Order_Time, dtype: object

In [7]:
num_cols = [
    'Customer_Age',
    'Delivery_Time_Min',
    'Distance_km',
    'Order_Value',
    'Discount_Applied'
]

for col in num_cols:
    df_clean[col] = df_clean[col].fillna(
        df_clean[col].median()
    )

In [8]:
cat_cols = [
    'Customer_Gender',
    'City',
    'Area',
    'Cuisine_Type',
    'Payment_Mode'
]

for col in cat_cols:
    df_clean[col] = df_clean[col].fillna(
        df_clean[col].mode()[0]
    )

In [10]:
df_clean['Final_Amount'] = (
    df_clean['Order_Value']
    -
    df_clean['Discount_Applied']
).clip(lower=0)

In [11]:
df_clean['Restaurant_Rating'] = (
    df_clean['Restaurant_Rating']
    .clip(upper=5)
)

In [12]:
df_clean.isnull().sum().sort_values(ascending=False)

Cancellation_Reason    90969
Peak_Hour              32962
Delivery_Rating        16523
Order_Time              1998
Order_Date              1014
Customer_ID                0
Customer_Age               0
Customer_Gender            0
Order_ID                   0
Cuisine_Type               0
Restaurant_Name            0
Restaurant_ID              0
Area                       0
City                       0
Order_Value                0
Delivery_Time_Min          0
Distance_km                0
Payment_Mode               0
Final_Amount               0
Discount_Applied           0
Order_Status               0
Delivery_Partner_ID        0
Restaurant_Rating          0
Order_Day                  0
Profit_Margin              0
dtype: int64

In [13]:
df_clean.to_csv(
    'cleaned_food_delivery.csv',
    index=False
)

In [14]:
df_clean['Order_Time'].sample(20)

80349    0:00
35950    0:00
13289    0:00
99381    0:00
90504    0:00
88851    0:00
85880    0:00
17761    0:00
84644    0:00
6803      NaN
28733    0:00
2069     0:00
33136    0:00
1122     0:00
54862    0:00
1269     0:00
11492    0:00
28609    0:00
97072    0:00
25942    0:00
Name: Order_Time, dtype: object

In [15]:
df_clean['Order_Time'].nunique()

1

In [16]:
pd.crosstab(
    df['Peak_Hour'],
    df['Order_Status']
)

Order_Status  Cancelled  Delivered
Peak_Hour
False              5021      28564
True               5083      28370

In [17]:
df_clean['Peak_Hour'] = df_clean['Peak_Hour'].fillna(
    df_clean['Peak_Hour'].mode()[0]
)

/tmp/ipykernel_3952/1629096874.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean['Peak_Hour'] = df_clean['Peak_Hour'].fillna(

In [18]:
pd.crosstab(
    df_clean['Order_Status'],
    df_clean['Delivery_Rating'].isnull()
)

Delivery_Rating  False  True
Order_Status
Cancelled        12561   2475
Delivered        70916  14048

In [19]:
df_clean['Delivery_Rating_Filled'] = df_clean['Delivery_Rating'].fillna(
    df_clean['Delivery_Rating'].median()
)

In [20]:
df_clean.isnull().sum().sort_values(ascending=False)

Cancellation_Reason       90969
Delivery_Rating           16523
Order_Time                 1998
Order_Date                 1014
Customer_ID                   0
Customer_Gender               0
Area                          0
Customer_Age                  0
City                          0
Order_ID                      0
Cuisine_Type                  0
Restaurant_Name               0
Restaurant_ID                 0
Delivery_Time_Min             0
Discount_Applied              0
Final_Amount                  0
Distance_km                   0
Order_Value                   0
Order_Status                  0
Payment_Mode                  0
Delivery_Partner_ID           0
Restaurant_Rating             0
Order_Day                     0
Peak_Hour                     0
Profit_Margin                 0
Delivery_Rating_Filled        0
dtype: int64

In [21]:
df_clean.to_csv(
    'cleaned_food_delivery.csv',
    index=False
)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [22]:
from google.colab import files
files.download('cleaned_food_delivery.csv')